output_folder: 'output'

corridor_list:
    'central':
        'data_path': 'path/folder'
    'norther':
        'data_path': 'path/folder'
    'lapsset':
        'data_path': 'path/folder'

corridor_list_test:
    'lapsset':
        'data_path': 'path/folder'
