points_folder: 'path/folder'
output_folder : 'path/output/folder'
corridors_data:
    'central':
        'csv_phr': 'file.csv'
        'csv_spot': 'file.csv'
        'output': 'path/output/folder'
    'lapsset':
        'csv_phr': 'file.csv'
        'csv_spot': 'file.csv'
        'output': 'path/output/folder'
    'northern':
        'csv_phr': 'file.csv'
        'csv_spot': 'file.csv'
        'output': 'path/output/folder'


